http:
  port: "8081"
  
salesforce:
  username: "andrecarlos@gmail.com"
  password: "bolota60"
  token: "dKHFmKulJRn9t5GcNYoBB1BFv"
  
file:
  accountsDir: "/Users/andre/Documents/CursoMule/MUFundamentals4.1_studentFiles_22sept2018/resources"
  
db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"